services:
  collector:
    image: musup-collector:latest
    restart: unless-stopped
    volumes:
      - /volume1/docker/musup/data:/data
    env_file: .env
    environment:
      DATA_DIR: /data
      ADMIN_PORT: "${COLLECTOR_PORT}"
    ports:
      - "${COLLECTOR_PORT}:${COLLECTOR_PORT}"


  processor:
    image: musup-processor:latest
    restart: unless-stopped
    volumes:
      - /volume1/docker/musup/data:/data
    env_file: .env
    environment:
      DATA_DIR: /data
    ports:
      - "${PROCESSOR_PORT}:8080"

